#IMPORTANT INFO: The AuthKnock creator (Mateusz Serafiński) does not provide 100% secure or bug-free software.

#By using AuthKnock you agree that you are using it at your own risk. The author is not responsible for any damage caused by using this software.

#This software is provided "as is" without any guarantees or warranty.

#This file can't be seen by the users that aren't administrators for security reasons. If the file is visible to non-admin users, please report a security issue, because the installation script should prevent this from happening.

#AuthKnock is not taking any of your data, but if you want to be safe, use a service account with minimal permissions.

#The creator of AuthKnock (Mateusz Serafiński) is not connected with any third-party services used in this software like MySQL. So report bugs only to at the official AuthKnock channels.

#------------ Security disclaimer ------------

# This authentication method using YAML file is NOT recommended for production environments due to security concerns. 

#Please consider using more secure authentication methods like MySQL or Active Directory. 

#For testing or small-scale deployments, ensure that this file is properly secured and access is restricted. 

#------------ End of disclaimer ------------

#You are using this method at your own risk!!!
users:

  - username: "admin_local"
    password_hash: "test" # providing here crypted password isn't making this methond more secure, The author does not recommend using this method in production environments.
    groups: ["admins", "authknock_users"]
    otp_secret: "MFYIL7KSSN2FNBVYUGS4QBJBETF2X7FE" # 16 character Base32 string for TOTP 2FA

  - username: "guest_user"
    password_hash: "abcdefg"
    groups: ["authknock_users", "produkcja_ssh"]
    otp_secret: "MFYIL7KSSN2FNBVYUGS4QBJBETF2X7FE" # 16 character Base32 string for TOTP 2FA