#IMPORTANT INFO: The AuthKnock creator (Mateusz Serafiński) does not provide 100% secure or bug-free software.
#By using AuthKnock you agree that you are using it at your own risk. The author is not responsible for any damage caused by using this software.
#This software is provided "as is" without any guarantees or warranty.
#This file can't be seen by the users that aren't administrators for security reasons. If the file is visible to non-admin users, please report a security issue, because the installation script should prevent this from happening.
#AuthKnock is not taking any of your data, but if you want to be safe, use a service account with minimal permissions.
#The creator of AuthKnock (Mateusz Serafiński) is not connected with any third-party services used in this software like Netgate. So report bugs only to at the official AuthKnock channels.
access_method: "api" # api / XMLRPC
username: "api_user"
password: "SuperSecretApiPassword123" # Ensure this file is secured properly, as it contains sensitive information like password.
url: https://example-pfsense-firewall.local/
client_id: ''
client_token: ''
verify_ssl: false # Set to true if using valid SSL certificates
